server:
  port: 8081
springdoc:
  api-docs:
    path: /doc
  swagger-ui:
    path: /
spring:
  application.name: Loan Service
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    hibernate.show-sql: true
    properties:
      hibernate.generate_statistics: false
  data:
    mongodb.uri: mongodb://user:123@localhost:8092/loan_db?authSource=admin
  datasource:
    hikari.connectionTimeout: 20000
    hikari.maximumPoolSize: 5
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8082/loan_db
    username: postgres
    password: 123
    initialization-mode: always
    initialize: true
  kafka:
    consumer:
      topic: user-credit-report
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      group-id: loan-processing-system-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      topic: user-credit-check
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
